import { StageParticipantInfo } from 'amazon-ivs-web-broadcast';
import { RemoteCommand, SDKCallbacks, SDKConfig } from './types';
export type ParticipantInfo = StageParticipantInfo;
interface CommunicationSDKInterface {
    initialize(): Promise<void>;
    startPublishing(): Promise<void>;
    stopPublishing(): void;
    toggleVideo(): void;
    toggleAudio(): void;
    setLocalAudioEnabled(enabled: boolean): void;
    setLocalVideoEnabled(enabled: boolean): void;
    getParticipants(): IterableIterator<ParticipantInfo>;
    getSelfId(): string | null;
    leaveStage(): void;
    muteParticipantAudio(participantId: string): void;
    unmuteParticipantAudio(participantId: string): void;
    muteParticipantVideo(participantId: string): void;
    unmuteParticipantVideo(participantId: string): void;
    getParticipantVolume(participantId: string): number;
    getParticipantCanvases(): Map<string, HTMLCanvasElement>;
    getParticipantCanvas(participantId: string): HTMLCanvasElement | null;
    createParticipantCanvas(participantId: string, container: HTMLElement): HTMLCanvasElement;
    removeParticipantCanvas(participantId: string): void;
    broadcastCommand(command: RemoteCommand, repeatCount?: number): Promise<boolean>;
}
export declare class CommunicationSDK implements CommunicationSDKInterface {
    private config;
    private callbacks;
    private stageManager;
    private publishManager;
    private participantManager;
    private mediaManager;
    private commandManager;
    private renderManager;
    private statusMonitor;
    constructor(config: SDKConfig, callbacks?: SDKCallbacks);
    initialize(): Promise<void>;
    startPublishing(): Promise<void>;
    stopPublishing(): void;
    toggleVideo(): void;
    toggleAudio(): void;
    setLocalAudioEnabled(enabled: boolean): void;
    setLocalVideoEnabled(enabled: boolean): void;
    getParticipants(): IterableIterator<ParticipantInfo>;
    getSelfId(): string | null;
    leaveStage(): void;
    muteParticipantAudio(participantId: string): void;
    unmuteParticipantAudio(participantId: string): void;
    muteParticipantVideo(participantId: string): void;
    unmuteParticipantVideo(participantId: string): void;
    getParticipantVolume(participantId: string): number;
    getParticipantCanvases(): Map<string, HTMLCanvasElement>;
    getParticipantCanvas(participantId: string): HTMLCanvasElement | null;
    createParticipantCanvas(participantId: string, container: HTMLElement): HTMLCanvasElement;
    removeParticipantCanvas(participantId: string): void;
    broadcastCommand(command: RemoteCommand, repeatCount?: number): Promise<boolean>;
    private getLocalStreamStatus;
    private updateParticipantStatus;
    private handleParticipantJoined;
    private handleParticipantLeft;
    private handleParticipantStreamsAdded;
    private handleParticipantStreamsRemoved;
}
export {};
